### ISSUE TITLE
Please remove unnecessary files

### ISSUE THREAD

**Issue by pcav** [Geolicious/geotweet#1]
.pyc etc.
Thanks.

**Comment by riccardoklinger** [comment]
What is "etc"?

Am Sonntag, 17. Mai 2015 schrieb Paolo Cavallini :

> .pyc etc.
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Geolicious/geotweet/issues/1.

## 

---

Geolicious GbR
Agentur für Geo-Kommunikation

Riccardo Klinger
Geschäftsführer

mobil: 0176 63437298
e-mail: riccardo.klinger@geolicious.de
web: www.geolicious.de

Geolicious GbR
c/o Daniel Kerkow
Binzstraße 48
13189 Berlin

Gesellschafter:
Riccardo Klinger
Daniel Kerkow
Jakob Hafner

Sitz der Gesellschaft: Berlin
Ust-ID: DE289107523

**Comment by pcav** [comment]
e.g. README.html and .txt (they should be compiled upon installation).
Thanks.

**Comment by riccardoklinger** [comment]
I've removed unnecessary files.
