### ISSUE TITLE
Better formatting for the About

### ISSUE THREAD

**Issue by pcav** [Geolicious/geotweet#2]
HTML is not interpreted:

twitter2qgis/geotweet collects tweets and store them in a shapefile. You need to install <a href="http://tweepy.readthedocs.org/en/v3.2.0/#" target="_blank">tweepy</a> prior usage and create API keys in your twitter account!

please use text (unsure rst is interpreted here).
Thanks.

**Comment by riccardoklinger** [comment]
I've removed the hotlinks.
